<a href="https://colab.research.google.com/github/Your-searcher/nastya_3/blob/main/%22Untitled3_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Создать массив из списков
import numpy as np
a = np.array([0, 2, 1])
print(a, type(a))
b = np.array([1, 4, 5, 8], float)
print(b, type(b))

[0 2 1] <class 'numpy.ndarray'>
[1. 4. 5. 8.] <class 'numpy.ndarray'>


In [ ]:
# Доступ к элеменам массива
import numpy as np
b = np.array([1, 4, 5, 8],
float)
print(b, type(b))
print(b[:2])
print(b[3])
b[0]=20
print(b)

[1. 4. 5. 8.] <class 'numpy.ndarray'>
[1. 4.]
8.0
[20.  4.  5.  8.]


In [ ]:
# Матрица
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]],
float)
print(a)
print(a[0,0])
print(a[0,1])

[[1. 2. 3.]
 [4. 5. 6.]]
1.0
2.0


In [ ]:
# Доступ к элеменам массива
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]],
float)
print(a)
print(a[1,:])
print(a[:,2])
print(a[-1:, -2:])

[[1. 2. 3.]
 [4. 5. 6.]]
[4. 5. 6.]
[3. 6.]
[[5. 6.]]


In [ ]:
# Метод shape возвращает количество строк и столбцов в матрице
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(a.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
(2, 3)


In [ ]:
# Метод dtype возвращает тип переменных, хранящихся в массиве
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]],
float)
print(a)
print(a.dtype)

[[1. 2. 3.]
 [4. 5. 6.]]
float64


In [ ]:
# Метод len возвращает длину первого измерения (оси)
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]],
float)
print(a)
print(len(a))
print(len(a[0]))

[[1. 2. 3.]
 [4. 5. 6.]]
2
3


In [ ]:
# Метод in используется для проверки на наличие элемента в массиве
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print(2 in a)
print(0 in a)

[[1. 2. 3.]
 [4. 5. 6.]]
True
False


In [ ]:
# Переформатировать одномерный массив из десяти элементов во двумерный массив, состоящий из пяти строк и двух столбцов
import numpy as np
a = np.array(range(10), float)
print(a)
a = a.reshape((5, 2))
print(a)
print(a.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
(5, 2)


In [ ]:
# Метод copy используется для создания копии существующего массива в памяти
import numpy as np
a = np.array([1, 2, 3], float)
b = a
c = a.copy()
a[0] = 0
print(a)
print(b)
print(c)
a[0]=7
print(b)
print(b)
print(c)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]
[7. 2. 3.]
[7. 2. 3.]
[1. 2. 3.]


In [ ]:
# Создание списков из массивов
import numpy as np
a = np.array([1, 2, 3], float)
print(a.tolist())
print(list(a))

[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]


In [ ]:
# Конвертация массива в бинарную строку
import numpy as np
a = np.array([1, 2, 3], float)
s = a.tostring()
print(s)
print(np.fromstring(s))

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'
[1. 2. 3.]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  This is separate from the ipykernel package so we can avoid doing imports until
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """


In [ ]:
# Заполнение массива одинаковым значением
import numpy as np
a = np.array([1, 2, 3],
float)
print(a)
a.fill(20)
print(a)

[1. 2. 3.]
[20. 20. 20.]


In [ ]:
# Транспонирование массивов
import numpy as np
a = np.array(range(6), float).reshape((2,3))
print(a)
print("Transpose")
print(a.transpose())

[[0. 1. 2.]
 [3. 4. 5.]]
Transpose
[[0. 3.]
 [1. 4.]
 [2. 5.]]


In [ ]:
# Многомерный массив можно переконвертировать в одномерный при помощи метода flatten
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)
print("Flatten")
b=a.flatten()
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]
Flatten
[1. 2. 3. 4. 5. 6.]


In [ ]:
# Два или больше массивов можно сконкатенировать при помощи метода concatenate
import numpy as np
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
print("А")
print(a)
print("В")
print(b)
print("С")
print(c)
print("Concatenate")
d=np.concatenate((a, b, c))
print(d)

А
[1. 2.]
В
[3. 4. 5. 6.]
С
[7. 8. 9.]
Concatenate
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
# Не одномерный массив можно соединить, создав ось
import numpy as np
a = np.array([[1, 2], [3, 4]],
float)
b = np.array([[5, 6], [7,8]], float)
print("A")
print(a)
print("B")
print(b)
print("Concatenate:")
c=np.concatenate((a,b))
print(c)
print("Concatenate axis=0")
d=np.concatenate((a,b), axis=0)
print(d)
print("Concatenate axis=1:")
e=np.concatenate((a,b), axis=1)
print(e)

A
[[1. 2.]
 [3. 4.]]
B
[[5. 6.]
 [7. 8.]]
Concatenate:
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenate axis=0
[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]
Concatenate axis=1:
[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


In [ ]:
# размерность массива может быть увеличена при использовании константы newaxis в квадратных скобках
import numpy as np
a = np.array([[1, 2], [3, 4]],
float)
b = np.array([[5, 6], [7,8]], float)
print("A:")
print(a)
print("B:")
print(b)
print("a[:,np.newaxis]:")
print(a[:,np.newaxis])
print("a[:,np.newaxis].shape:")
print(a[:,np.newaxis].shape)
print("[np.newaxis,:]")
print(b[np.newaxis,:])
print("b[np.newaxis,:].shape")
print(b[np.newaxis,:].shape)

A:
[[1. 2.]
 [3. 4.]]
B:
[[5. 6.]
 [7. 8.]]
a[:,np.newaxis]:
[[[1. 2.]]

 [[3. 4.]]]
a[:,np.newaxis].shape:
(2, 1, 2)
[np.newaxis,:]
[[[5. 6.]
  [7. 8.]]]
b[np.newaxis,:].shape
(1, 2, 2)


In [ ]:
# Функция arange аналогична функции range, но возвращает массив
import numpy as np
a=np.arange(5, dtype=float)
print(a)
print()
b=np.arange(1, 10, 2, dtype=int)
print(b)

[0. 1. 2. 3. 4.]

[1 3 5 7 9]


In [ ]:
# Создание массивов
import numpy as np
a=np.ones((2,3), dtype=float)
b=np.zeros(7, dtype=int)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 0 0 0 0 0 0]


In [ ]:
# Преобразование уже созданных массивов, заполнив его нулями и единицами соответственно
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]],
float)
b=np.zeros_like(a)
c= np.ones_like(a)
print("A:")
print(a)
print("B:")
print(b)
print("C:")
print(c)

A:
[[1. 2. 3.]
 [4. 5. 6.]]
B:
[[0. 0. 0.]
 [0. 0. 0.]]
C:
[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Создание квадратичной матрицы
import numpy as np
a=np.identity(4, dtype=float)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
# Функция eye возвращает матрицу с единичками на к-атой диагонали
import numpy as np
a=np.eye(4, k=1, dtype=float)
print(a)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [ ]:
# Соблюдение принципа элемент-элемент
import numpy as np
a = np.array([1,2,3], float)
b = np.array([5,2,6],
float)
print("A:")
print(a)
print("B:")
print(b)
print("A+B")
print(a+b)
print("A-B:")
print(a-b)
print("A*B:")
print(a*b)
print("A/B:")
print(a/b)
print("A%B:")
print(a%b)
print("B^A:")
print(b**a)

A:
[1. 2. 3.]
B:
[5. 2. 6.]
A+B
[6. 4. 9.]
A-B:
[-4.  0. -3.]
A*B:
[ 5.  4. 18.]
A/B:
[0.2 1.  0.5]
A%B:
[1. 0. 3.]
B^A:
[  5.   4. 216.]


In [ ]:
# Умножение двумерных массивов
import numpy as np
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
c=a * b
print(c)

[[ 2.  0.]
 [ 3. 12.]]


In [ ]:
# При несоответствии в размере выбрасываются ошибки
import numpy as np
a = np.array([1,2,3], float)
b = np.array([4,5], float)
c=a + b
print(c)

ValueError: ignored

In [ ]:
# Пример
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print("A:")
print(a)
print("B:")
print(b)
print("A+B")
print(a+b)

A:
[[1. 2.]
 [3. 4.]
 [5. 6.]]
B:
[-1.  3.]
A+B
[[0. 5.]
 [2. 7.]
 [4. 9.]]


In [ ]:
# константа newaxis
import numpy as np
a = np.zeros((2,2), float)
b = np.array([-1., 3.], float)
print("A:")
print(a)
print("B:")
print(b)
print("A+B:")
print(a+b)
print("a + b[np.newaxis,:]:")
print(a + b[np.newaxis,:])
print("a + b[:,np.newaxis]:")
print(a + b[:,np.newaxis])

A:
[[0. 0.]
 [0. 0.]]
B:
[-1.  3.]
A+B:
[[-1.  3.]
 [-1.  3.]]
a + b[np.newaxis,:]:
[[-1.  3.]
 [-1.  3.]]
a + b[:,np.newaxis]:
[[-1. -1.]
 [ 3.  3.]]


In [ ]:
# sqrt
import numpy as np
a = np.array([1, 4, 9], float)
print("A:")
print(a)
print("sqrt(a):")
b=np.sqrt(a)
print(b)

A:
[1. 4. 9.]
sqrt(a):
[1. 2. 3.]


In [ ]:
# Функции floor, ceil и rint возвращают нижние, верхние или ближайшие (округлённое) значение:
import numpy as np
a = np.array([1.1, 1.5, 1.9], float)
print("A:")
print(a)
print("floor(a):")
b=np.floor(a)
print(b)
print("ceil(a):")
c=np.ceil(a)
print(c)
print("rint(a):")
d=np.rint(a)
print(d)

A:
[1.1 1.5 1.9]
floor(a):
[1. 1. 1.]
ceil(a):
[2. 2. 2.]
rint(a):
[1. 2. 2.]


In [ ]:
# Константы
import numpy as np
print("PI:", np.pi)
print("E:", np.e)

PI: 3.141592653589793
E: 2.718281828459045


In [ ]:
# Проводить итерацию массивов можно аналогично спискам
import numpy as np
a = np.array([1, 4, 5], int)
for x in a:
  print(x)

1
4
5


In [ ]:
# Для многомерных массивов итерация будет проводиться по первой оси, так, что каждый проход цикла будет возвращать «строку» массива
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
  print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [ ]:
# Множественное присваивание также доступно при итерации
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6]], float)
fr (x, y) in a:
  print (x * y)

2.0
12.0
30.0


In [ ]:
# Для получения каких-либо свойств массивов существует много функций. Элементы могут быть суммированы или перемножены
import numpy as np
a = np.array([2, 4, 3], float)
S= a.sum()
P=a.prod()
print("S=",S, "P=",P)

S= 9.0 P= 24.0


In [ ]:
# Функции numpy
import numpy as np
a = np.array([2, 4, 3], float)
S= np.sum(a)
P=np.prod(a)
print("S=",S, "P=",P)

S= 9.0 P= 24.0


In [ ]:
# Aункции mean (среднее арифметическое), вариация и девиация:
import numpy as np
a = np.array([2, 1, 9], float)
SA=a.mean()
Var=a.var()
Dev=a.std()
print("SA=", SA, "Var=", Var, "Dev=", Dev)

SA= 4.0 Var= 12.666666666666666 Dev= 3.559026084010437


In [ ]:
# Vинимум и максимум в массиве
import numpy as np
a = np.array([2, 1, 9], float)
Min=a.min()
Max= a.max()
print("Min=", Min, "Max=", Max)

Min= 1.0 Max= 9.0


In [ ]:
# Функции argmin и argmax возвращают индекс минимального или максимального элемента
import numpy as np
a = np.array([2, 1, 9,4,6,15], float)
Imin=a.argmin()
Imax= a.argmax()
print("Imin=", Imin, " Imax=", Imax)

Imin= 1  Imax= 5


In [ ]:
# Макс и мин
import numpy as np
a = np.array([[0, 2], [3, -1], [3, 5]], float)
print(a)
print()
M0=a.mean(axis=0)
M1=a.mean(axis=1)
print("Mean0=", M0)
print("Mean1=", M1)
Min1= a.min(axis=1)
Max0= a.max(axis=0)
print("Min1=", Min1)
print("Max0=", Max0)

[[ 0.  2.]
 [ 3. -1.]
 [ 3.  5.]]

Mean0= [2. 2.]
Mean1= [1. 1. 4.]
Min1= [ 0. -1.  3.]
Max0= [3. 5.]


In [ ]:
# Как и списки, массивы можно отсортировать
import numpy as np
a = np.array([6, 2, 5, -1, 0], float)
b=sorted(a)
print(b)
c=a.sort()
print(c)

[-1.0, 0.0, 2.0, 5.0, 6.0]
None


In [ ]:
# Значения в массиве могут быть «сокращены», чтобы принадлежать заданному диапазону
import numpy as np
a = np.array([6, 2, 5, -1, 0], float)
print(a)
b= a.clip(0, 5)
print(b)

[ 6.  2.  5. -1.  0.]
[5. 2. 5. 0. 0.]


In [ ]:
#
import numpy as np
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
print(a)
b=np.unique(a)
print(b)

[1. 1. 4. 5. 5. 5. 7.]
[1. 4. 5. 7.]


In [ ]:
# Уникальные элементы могут быть извлечены
import numpy as np
a = np.array([[1, 2], [3, 4]], float)
print(a)
print()
b=a.diagonal()
print(b)

[[1. 2.]
 [3. 4.]]

[1. 4.]


In [ ]:
# Для двухмерных массивов диагональ
import numpy as np
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
print("A:")
print(a)
print("B:")
print(b)
c=a > b
print("a>b:")
print(c)
d=a == b
print("a==b:")
print(d)
e=a < b
print("a<=b:")
print(e)

A:
[1. 3. 0.]
B:
[0. 3. 2.]
a>b:
[ True False False]
a==b:
[False  True False]
a<=b:
[False False  True]


In [ ]:
# Массивы могут быть сравнены с одиночным значением:
import numpy as np
a = np.array([1, 3, 0], float)
print("A:")
print(a)
b=a > 2
print("a>2:")
print(b)

A:
[1. 3. 0.]
a>2:
[False  True False]


In [ ]:
# Операторы any и all могут быть использованы для определения истинны ли хотя бы один или все элементы соответственно
import numpy as np
a = np.array([ True, False, False], bool)
print("A:")
print(a)
print("Any:")
b=any(a)
print(b)
print("All:")
c=all(a)
print(c)

A:
[ True False False]
Any:
True
All:
False


In [ ]:
# Комбинированные булевы выражения могут быть применены к
# массивам по принципу элемент — элемент используя специальные функции
# logical_and, logical_or и logical_not:
import numpy as np
a = np.array([1, 3, 0], float)
aland=np.logical_and(a > 0, a < 3)
print("A:")
print(a)
print("logical_and(a > 0, a <; 3)")
print(aland)
b = np.array([True, False, True], bool)
blnot= np.logical_not(b)
print("B:")
print(b)
print("logical_not(b)")
print(blnot)
c = np.array([False, True, False], bool)
clor=np.logical_or(b, c)
print("C:")
print(c)
print("logical_or(b, c)")
print(clor)

A:
[1. 3. 0.]
logical_and(a > 0, a <; 3)
[ True False False]
B:
[ True False  True]
logical_not(b)
[False  True False]
C:
[False  True False]
logical_or(b, c)
[ True  True  True]


In [ ]:
# Массовое сравнение
import numpy as np
a = np.array([1, 3, 0], float)
b=np.where(a  > 0, 3, 2)
print("A:")
print(a)
print("where(a > 0, 3, 2):")
print(b)

A:
[1. 3. 0.]
where(a > 0, 3, 2):
[3 3 2]


In [ ]:
# Функция nonzero возвращает кортеж индексов ненулевых значений
import numpy as np
a=np.array([[0, 1], [3, 0]], float)
b=a.nonzero()
print("A:")
print(a)
print("B:")
print(b)

A:
[[0. 1.]
 [3. 0.]]
B:
(array([0, 1]), array([1, 0]))


In [ ]:
# Проверка значения на конечность и NaN(not a number):
import numpy as np
a = np.array([1, np.NaN, np.Inf],
float)
print("A:")
print(a)
b= np.isnan(a)
print("isNan(a):")
print(b)
c=np.isfinite(a)
print("isfinite(a):")
print(c)

A:
[ 1. nan inf]
isNan(a):
[False  True False]
isfinite(a):
[ True False False]


In [ ]:
# Задание 1.
import numpy as np
x = np.linspace(-2 * np.pi, 2 * np.pi, 20)
print("x:")
print(x)
y=np.sin(x)**2 + np.cos(x)**2
print("y")
print(y)
z=np.all((np.sin(x)**2 + np.cos(x)**2).round() == 1)
print("z:")
print(z)

x:
[-6.28318531 -5.62179738 -4.96040945 -4.29902153 -3.6376336  -2.97624567
 -2.31485774 -1.65346982 -0.99208189 -0.33069396  0.33069396  0.99208189
  1.65346982  2.31485774  2.97624567  3.6376336   4.29902153  4.96040945
  5.62179738  6.28318531]
y
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
z:
True


In [ ]:
print("For1. Даны целые числа K и N (N > 0). Вывести N раз число K.")
n = 5
k = 4
for i in range(n):
  print(k)

For1. Даны целые числа K и N (N > 0). Вывести N раз число K.
4
4
4
4
4


In [ ]:
print("For11. Дано целое число N (> 0). Найти произведение 1.1 * 1.2 * 1.3 * . . .")
n = 5
k = 1.1
proiz = k
for i in range(n-1):
  k+=0.1
  proiz*=k
print(proiz)

For11. Дано целое число N (> 0). Найти произведение 1.1 * 1.2 * 1.3 * . . .
3.6036000000000032
